title: Christopher Brasington
description: >-
  Software engineer in Denver, Colorado. Project portfolio and writings on
  open-source tools, gaming, Morrowind modding, and reclaiming your attention
  from the modern internet.
url: https://chrisincode.com
name: Christopher Brasington
author: Christopher Brasington
lang: en-US
timezone: America/Denver

twitter:
  card: summary
social:
  name: Christopher Brasington
  links:
    - https://github.com/chrisbrasington
    - https://www.linkedin.com/in/brasington/

markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# theme: minima
# theme: dinky
# theme: hacker
# theme: leap-day
# theme: merlot
# theme: minimal
# theme: modernist
# theme: tactile
#theme: jekyll-theme-cayman
#theme: jekyll-theme-midnight
theme: jekyll-theme-slate
#theme: jekyll-theme-time-machine
