# title: CB io
markdown: kramdown
# theme: minima
# theme: cayman
# theme: dinky
# theme: hacker
# theme: leap-day
# theme: merlot
# theme: midnight
# theme: minimal
# theme: modernist
# theme: slate
# theme: tactile
theme: time-machine
